project_id = "rvjlpzahlcgfdxecrjkq"

[functions.airtable-submit]
verify_jwt = false

[functions.send-my-finds]
verify_jwt = false

[functions.update-trending-merchants]
verify_jwt = false

[functions.admin-send-merchant-email]
verify_jwt = false